#default_responders = ""

# Define custom statuses for your detection lifecycle
# Uncomment and customize these examples to match your organization's workflow
# By default there are base statuses maintained within CoreTide, and adding any [[statuses]]
# entry will override all of them to allow you full customisation
#[[statuses]]
#name = "DEVELOPMENT"
#description = "Initial development phase - detections are being written and tested"
#strategy = "PREVIEW"

#[[statuses]]
#name = "TESTING"
#description = "Quality assurance phase - detections are being validated in a test environment"
#strategy = "PREVIEW"

#[[statuses]]
#name = "PRODUCTION"
#description = "Live deployment - detections are actively monitoring in production"
#strategy = "RELEASE"

[promotion]
#enabled = true
#promotion_target = "PRODUCTION"

[proxy]
#proxy_user = "$PROXY_USER"
#proxy_password = "$PROXY_PASSWORD"
#proxy_host = "$PROXY_HOST"
#proxy_port = "$PROXY_PORT"

# If enabled, updates a lookup continuously with MDR Data. Often useful to
# have access to MDR Data directly on external systems, e.g. for alert enriching
[metadata_lookup]
#enabled = false
#name = ""
#systems = ["splunk"]